#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v7
# autospec commit: f56f1fa
#
Name     : R-ape
Version  : 5.8
Release  : 65
URL      : https://cran.r-project.org/src/contrib/ape_5.8.tar.gz
Source0  : https://cran.r-project.org/src/contrib/ape_5.8.tar.gz
Summary  : Analyses of Phylogenetics and Evolution
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
Requires: R-ape-lib = %{version}-%{release}
Requires: R-ape-license = %{version}-%{release}
Requires: R-Rcpp
Requires: R-digest
BuildRequires : R-Rcpp
BuildRequires : R-digest
BuildRequires : buildreq-R

%description
# ape
This is the development version of ape.
To know more about ape: https://emmanuelparadis.github.io

%package lib
Summary: lib components for the R-ape package.
Group: Libraries
Requires: R-ape-license = %{version}-%{release}

%description lib
lib components for the R-ape package.


%package license
Summary: license components for the R-ape package.
Group: Default

%description license
license components for the R-ape package.


%prep
%setup -q -n ape
pushd ..
cp -a ape buildavx2
popd
pushd ..
cp -a ape buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1712850816

%install
export SOURCE_DATE_EPOCH=1712850816
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-ape
cp %{_builddir}/ape/COPYING %{buildroot}/usr/share/package-licenses/R-ape/b47456e2c1f38c40346ff00db976a2badf36b5e3 || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/ape/CITATION
/usr/lib64/R/library/ape/DESCRIPTION
/usr/lib64/R/library/ape/INDEX
/usr/lib64/R/library/ape/Meta/Rd.rds
/usr/lib64/R/library/ape/Meta/data.rds
/usr/lib64/R/library/ape/Meta/features.rds
/usr/lib64/R/library/ape/Meta/hsearch.rds
/usr/lib64/R/library/ape/Meta/links.rds
/usr/lib64/R/library/ape/Meta/nsInfo.rds
/usr/lib64/R/library/ape/Meta/package.rds
/usr/lib64/R/library/ape/Meta/vignette.rds
/usr/lib64/R/library/ape/NAMESPACE
/usr/lib64/R/library/ape/NEWS
/usr/lib64/R/library/ape/R/ape
/usr/lib64/R/library/ape/R/ape.rdb
/usr/lib64/R/library/ape/R/ape.rdx
/usr/lib64/R/library/ape/data/HP.links.rda
/usr/lib64/R/library/ape/data/bird.families.rda
/usr/lib64/R/library/ape/data/bird.orders.rda
/usr/lib64/R/library/ape/data/carnivora.csv.gz
/usr/lib64/R/library/ape/data/chiroptera.rda
/usr/lib64/R/library/ape/data/cynipids.rda
/usr/lib64/R/library/ape/data/gopher.D.rda
/usr/lib64/R/library/ape/data/hivtree.newick.rda
/usr/lib64/R/library/ape/data/hivtree.table.txt.gz
/usr/lib64/R/library/ape/data/lice.D.rda
/usr/lib64/R/library/ape/data/lmorigin.ex1.rda
/usr/lib64/R/library/ape/data/lmorigin.ex2.rda
/usr/lib64/R/library/ape/data/mat3.RData
/usr/lib64/R/library/ape/data/mat5M3ID.RData
/usr/lib64/R/library/ape/data/mat5Mrand.RData
/usr/lib64/R/library/ape/data/woodmouse.rda
/usr/lib64/R/library/ape/doc/DrawingPhylogenies.R
/usr/lib64/R/library/ape/doc/DrawingPhylogenies.Rnw
/usr/lib64/R/library/ape/doc/DrawingPhylogenies.pdf
/usr/lib64/R/library/ape/doc/MoranI.R
/usr/lib64/R/library/ape/doc/MoranI.Rnw
/usr/lib64/R/library/ape/doc/MoranI.pdf
/usr/lib64/R/library/ape/doc/RandomTopologies.R
/usr/lib64/R/library/ape/doc/RandomTopologies.Rnw
/usr/lib64/R/library/ape/doc/RandomTopologies.pdf
/usr/lib64/R/library/ape/doc/index.html
/usr/lib64/R/library/ape/help/AnIndex
/usr/lib64/R/library/ape/help/aliases.rds
/usr/lib64/R/library/ape/help/ape.rdb
/usr/lib64/R/library/ape/help/ape.rdx
/usr/lib64/R/library/ape/help/paths.rds
/usr/lib64/R/library/ape/html/00Index.html
/usr/lib64/R/library/ape/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/ape/libs/ape.so
/V4/usr/lib64/R/library/ape/libs/ape.so
/usr/lib64/R/library/ape/libs/ape.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-ape/b47456e2c1f38c40346ff00db976a2badf36b5e3
